# Generated by Django 6.0 on 2026-01-09 20:53

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, help_text="User's monthly income in currency", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('necessary_needs', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly expenses for rent, EMI, groceries, etc.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('goals_and_wants', models.TextField(blank=True, help_text="User's goals and wants (JSON format or text)")),
                ('monthly_unwanted_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit for unwanted/discretionary spending', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
